# Site settings
title: Brian Davis's Resume
description: mrbriandavis CV
favicon: /assets/img/avatar.jpeg
# baseurl: http://resume.mrbriandavis/
# url: http://resume.mrbriandavis
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Brian Davis
  title: Engineer
  address: Redmond, Washington
  email: mrbriandavis@outlook.com
  link: http://mrbriandavis.com
  weibo:
  github: mrbriandavis
  linkedin: brian-davis-9a702158
  twitter: mrbriandavis
  gavatar: favicon
  workHistory:
    - work1:
      company: Microsoft
      location: Redmond, Washington
      title: Backend Services Developer
      started: 2015
      duration: (2015 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Microsoft
      location: San Francisco, California
      title: Software Engineer in Test II
      started: 2013
      duration: (2013 - 2015)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Microsoft | Yammer
      location: Phoenix, Arizona
      title: Solutions Engineer
      started: 2012
      duration: (2012 - 2013)
      description: "Some basic instructions"
      description_duties:
        ["Synchronizing customers Yammer network accounts with their existing Active Directory system", "Installing and configuring Yammers SharePoint Web Part into their existing SharePoint systems",
          "Implementing SAML based Single Sign On authentication between the customers users and Yammer.coms Ping server.",
           "RESTful API support/development"]
    - work4:
      company: Western Maricopa Education Center
      location: Phoenix, Arizona
      title: IT Coordinator
      started: 2011
      duration: (2011 - 2012)
      description: Communicating problems and solutions and providing PC and system related education as appropriate.
  educationHistory:
    - education1:
      organization: Northern Arizona University
      degree: Bachelor
      major: Education
      started: 2000
      duration: (2000 - 2004)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  # languages:
  #   - language1:
  #     name: Chinese
  #     proficiency: Native
  #   - language2:
  #     name: English
  #     proficiency: Professional
  #   - language3:
  #     name: Japanese
  #     proficiency: Limit
  programmingSkills:
    - skill1:
      name: Ruby
      percentage: 80%
    - skill2:
      name: Java
      percentage: 70%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: HTML
      percentage: 80%
